### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by rubiktubik** [Bomret/NeverNull#12]
Hi,

awesome library.
Is .NET Core support planned?

rubiktubik

**Comment by Bomret** [comment]
Hi Michael,

Yes, I just didn’t have time to do that, yet. I want to go straight to netstandard support, but this might take a while. Or do you want to help out with that?

Cheers,
Stefan

**Comment by rubiktubik** [comment]
Hi,
I don't have much time either :-)
But if i have some time i would be glad to help you.

Michael

**Comment by Bomret** [comment]
The whole lib is netstandard now so there should be no problem with .net core projects
